name: Lint

on:
  push:
    branches:
      - dev/clean_forecast
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install ruff

      - name: Run Ruff
        run: |
          ruff check .

    outputs:
      trigger_type: ${{ github.event_name }}

    if: ${{ github.event_name == 'push' }}
